# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f361d6ca924b47fca5b3f2ca6f3f4432cdfdb70656264d4cceb6150e8a81c60efc76fc88b60965fd18d9b931ca6cc543f593c4eeaa40b99838d3d1bbb2d2348b

test:
  secret_key_base: 5df7aeae11ea9f319bf0aad26c1ce83b62f442dc9f18e8618bd8f5ef59072be691345e6127d8b69838b593e9aca6623981fd5f79a79b4ef5cf53663983d6a90d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
